spring:
  datasource:
    url: jdbc:h2:mem:userspetsdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    try-it-out-enabled: true
    path: /swagger-ui/index.html
  logging:
    level:
      com.example.app: INFO   # or DEBUG for more detailed logs
